DELETE FROM user_authority;
DELETE FROM user_experience;
DELETE FROM user_study;
DELETE FROM feedback;
DELETE FROM _user;
DELETE FROM study;
DELETE FROM experience;
DELETE FROM role;
DELETE FROM authority;